ar2723/Acorn_Team_Project

- Soso/src/main/webapp/WEB-INF/views/test/test.jsp
> 23.07.27 / 22:21 / PR 테스트

- Soso/src/main/java/com/acorn/soso/group/controller/GroupController.java
- Soso/src/main/java/com/acorn/soso/group/dao/GroupJoinDao.java
- Soso/src/main/java/com/acorn/soso/group/dao/GroupJoinDaoImpl.java
- Soso/src/main/java/com/acorn/soso/group/dto/GroupJoinDto.java
- Soso/src/main/java/com/acorn/soso/group/service/GroupService.java
- Soso/src/main/java/com/acorn/soso/group/service/GroupServiceImpl.java
- Soso/src/main/resources/mapper/JoinMapper.xml
- Soso/src/main/webapp/WEB-INF/table.sql
- Soso/src/main/webapp/WEB-INF/views/group/group_in.jsp
- Soso/src/main/webapp/WEB-INF/views/group/test.jsp
1. table에 join table 양식 작성
2. contoller, dto, dao, service 작성(나중에 수정&병합의 여지 있음)
3. 확인은 test->가입하기 버튼 눌러서 확인하면 됨
> 김형규_소모임 가입기능 구현(08/02)

- Soso/src/main/java/com/acorn/soso/group/controller/GroupController.java
- Soso/src/main/java/com/acorn/soso/group/service/GroupServiceImpl.java
- Soso/src/main/webapp/WEB-INF/views/group/group_page.jsp
- Soso/src/main/webapp/WEB-INF/views/group/list.jsp
- Soso/src/main/webapp/WEB-INF/views/include/navbar.jsp
> list에 group_page 추가하고 찜 리스트 nav에 연결

- Soso/src/main/java/com/acorn/soso/support/controller/SupportController.java
- Soso/src/main/webapp/WEB-INF/views/support/support_faq.jsp
- Soso/src/main/webapp/WEB-INF/views/support/support_faq_etc.jsp
- Soso/src/main/webapp/WEB-INF/views/support/support_faq_open.jsp
- Soso/src/main/webapp/WEB-INF/views/support/support_faq_request.jsp
- Soso/src/main/webapp/WEB-INF/views/support/support_faq_user.jsp
- Soso/src/main/webapp/WEB-INF/views/support/support_inquire_MyInquire.jsp
- Soso/src/main/webapp/WEB-INF/views/support/support_inquire_register.jsp
8월9일 자주하는 질문 및 문의사항 레이아웃 수정 및 추가
> 8월9일 자주하는 질문 및 문의사항 레이아웃 수정 및 추가

- Soso/src/main/java/com/acorn/soso/group/controller/GroupController.java
- Soso/src/main/java/com/acorn/soso/group/dto/GroupDto.java
- Soso/src/main/java/com/acorn/soso/group/service/GroupService.java
- Soso/src/main/java/com/acorn/soso/group/service/GroupServiceImpl.java
- Soso/src/main/resources/mapper/GroupMapper.xml
- Soso/src/main/webapp/WEB-INF/views/group/list.jsp
- Soso/src/main/webapp/WEB-INF/views/home.jsp
- Soso/src/main/webapp/resources/css/common.css
- Soso/src/main/webapp/resources/css/group_list.css
23.08.09 / group list 페이지 검색 기능 구현
> 23.08.09 / group list 페이지 검색 기능 구현

- Soso/src/main/java/com/acorn/soso/group/controller/GroupController.java
- Soso/src/main/java/com/acorn/soso/group/dao/GroupDao.java
- Soso/src/main/java/com/acorn/soso/group/dao/GroupDaoImpl.java
- Soso/src/main/java/com/acorn/soso/group/dao/GroupJoinDao.java
- Soso/src/main/java/com/acorn/soso/group/dao/GroupJoinDaoImpl.java
- Soso/src/main/java/com/acorn/soso/group/service/GroupService.java
- Soso/src/main/java/com/acorn/soso/group/service/GroupServiceImpl.java
- Soso/src/main/resources/mapper/JoinMapper.xml
- Soso/src/main/webapp/WEB-INF/views/group/group_page.jsp
- Soso/src/main/webapp/WEB-INF/views/group/jjim_list.jsp
> 가입하기 & 가입 신청 취소 기능 구현하고 로그인 안해도 페이지 들어갈 수 있도록 수정

- Soso/src/main/java/com/acorn/soso/support/faq/dao/FaqDao.java
- Soso/src/main/java/com/acorn/soso/support/faq/dto/FaqDto.java
- Soso/src/main/webapp/WEB-INF/views/support/support_faq.jsp
- Soso/src/main/webapp/WEB-INF/views/support/support_faq_etc.jsp
- Soso/src/main/webapp/WEB-INF/views/support/support_faq_open.jsp
- Soso/src/main/webapp/WEB-INF/views/support/support_faq_request.jsp
- Soso/src/main/webapp/WEB-INF/views/support/support_faq_user.jsp
- Soso/src/main/webapp/WEB-INF/views/support/support_inquire.jsp
- Soso/src/main/webapp/WEB-INF/views/support/support_inquire_MyInquire.jsp
- Soso/src/main/webapp/WEB-INF/views/support/support_inquire_register.jsp
- Soso/src/main/webapp/WEB-INF/views/support/support_main.jsp
- Soso/src/main/webapp/WEB-INF/views/support/support_notice.jsp
> 8월10일 레이아웃 수정 및 추가, dto 추가

- Soso/src/main/java/com/acorn/soso/group/controller/GroupController.java
- Soso/src/main/java/com/acorn/soso/group/dto/JjimDto.java
- Soso/src/main/java/com/acorn/soso/group/service/GroupServiceImpl.java
- Soso/src/main/resources/mapper/JjimMapper.xml
- Soso/src/main/webapp/WEB-INF/views/group/faq/group_faq_update_form.jsp
- Soso/src/main/webapp/WEB-INF/views/group/faq/insertform.jsp
- Soso/src/main/webapp/WEB-INF/views/group/faq/list.jsp
- Soso/src/main/webapp/WEB-INF/views/group/group_page.jsp
> Detail page

- Soso/src/main/java/com/acorn/soso/group/controller/GroupController.java
- Soso/src/main/java/com/acorn/soso/group/dto/GroupFAQDto.java
- Soso/src/main/java/com/acorn/soso/group/service/GroupServiceImpl.java
- Soso/src/main/webapp/WEB-INF/views/cafe/insertform.jsp
- Soso/src/main/webapp/WEB-INF/views/group/faq/insertform.jsp
- Soso/src/main/webapp/WEB-INF/views/group/faq/list.jsp
- Soso/src/main/webapp/WEB-INF/views/group/group_page.jsp
> groupPage 오류 수정하고, GroupServiceImpl 주석처리한거 원복

- Soso/src/main/java/com/acorn/soso/group_managing/controller/GroupManagingController.java
- Soso/src/main/java/com/acorn/soso/group_managing/dao/GroupManagingDao.java
- Soso/src/main/java/com/acorn/soso/group_managing/dao/GroupManagingDaoImpl.java
- Soso/src/main/java/com/acorn/soso/group_managing/service/GroupManagingService.java
- Soso/src/main/java/com/acorn/soso/group_managing/service/GroupManagingServiceImpl.java
- Soso/src/main/resources/mapper/GroupManagingMapper.xml
- Soso/src/main/webapp/WEB-INF/views/group_managing/group_userdetail.jsp
- Soso/src/main/webapp/WEB-INF/views/group_managing/user_main.jsp
Controller/Dao/DaoImpl/Dto/Service/ServiceImpl/Mapper 추가
> group_user main / detail 수정 사항 및 GroupManaging

- Soso/src/main/java/com/acorn/soso/group/service/GroupService.java
- Soso/src/main/java/com/acorn/soso/group/service/GroupServiceImpl.java
- Soso/src/main/webapp/WEB-INF/views/group/group_page.jsp
- Soso/src/main/webapp/WEB-INF/views/group/list.jsp
- Soso/src/main/webapp/WEB-INF/views/group/viewList.jsp
- Soso/src/main/webapp/resources/css/group_list.css
신청기간 마감시 마감으로 변경, 썸네일에 마감 버튼 띄우기
> Hn#230811 

- Soso/src/main/java/com/acorn/soso/group/controller/GroupController.java
- Soso/src/main/java/com/acorn/soso/group/dao/GroupDao.java
- Soso/src/main/java/com/acorn/soso/group/dao/GroupDaoImpl.java
- Soso/src/main/java/com/acorn/soso/group/service/GroupService.java
- Soso/src/main/java/com/acorn/soso/group/service/GroupServiceImpl.java
- Soso/src/main/resources/mapper/GroupMapper.xml
- Soso/src/main/webapp/WEB-INF/views/group/list.jsp
- Soso/src/main/webapp/WEB-INF/views/group/viewList.jsp
230815/소모임 카테고리 별 리스트 출력 기능 구현
> 230815/소모임 카테고리 별 리스트 출력 기능 구현

- Soso/src/main/java/com/acorn/soso/support/controller/SupportController.java
- Soso/src/main/java/com/acorn/soso/support/faq/dao/FaqDao.java
- Soso/src/main/java/com/acorn/soso/support/faq/dao/FaqDaoImpl.java
- Soso/src/main/java/com/acorn/soso/support/faq/dto/FaqDto.java
- Soso/src/main/java/com/acorn/soso/support/faq/service/FaqService.java
- Soso/src/main/java/com/acorn/soso/support/faq/service/FaqServiceImpl.java
- Soso/src/main/resources/mapper/support/FaqMapper.xml
- Soso/src/main/webapp/WEB-INF/views/support/support_faq.jsp
- Soso/src/main/webapp/WEB-INF/views/support/support_faq_insert.jsp
- Soso/src/main/webapp/WEB-INF/views/support/support_faq_insertform.jsp
- Soso/src/main/webapp/WEB-INF/views/support/support_main.jsp
- Soso/src/main/webapp/resources/css/support/support_main.css
> 8월 16일 faq 내용 추가

- Soso/src/main/java/com/acorn/soso/support/controller/SupportController.java
- Soso/src/main/java/com/acorn/soso/support/faq/dao/FaqDaoImpl.java
- Soso/src/main/resources/application.properties
- Soso/src/main/resources/mapper/support/FaqMapper.xml
- Soso/src/main/webapp/WEB-INF/views/support/support_faq.jsp
- Soso/src/main/webapp/WEB-INF/views/support/support_faq_etc.jsp
- Soso/src/main/webapp/WEB-INF/views/support/support_faq_insertform.jsp
- Soso/src/main/webapp/WEB-INF/views/support/support_faq_open.jsp
- Soso/src/main/webapp/WEB-INF/views/support/support_faq_request.jsp
- Soso/src/main/webapp/WEB-INF/views/support/support_faq_user.jsp
8월 16일 faq 자주하는 질문 등록 및 출력 기능 추가
> 8월 16일 faq 자주하는 질문 등록 및 출력 기능 추가

- Soso/src/main/webapp/WEB-INF/views/group/list.jsp
- Soso/src/main/webapp/WEB-INF/views/group_managing/admin_main.jsp
- Soso/src/main/webapp/WEB-INF/views/group_managing/user_main.jsp
- Soso/src/main/webapp/WEB-INF/views/home.jsp
- Soso/src/main/webapp/WEB-INF/views/include/navbar.jsp
- Soso/src/main/webapp/resources/css/common.css
- Soso/src/main/webapp/resources/css/group_managing_user_main.css
- Soso/src/main/webapp/resources/css/main.css
> 230816/나의 북메이트 페이지 UI 수정

- Soso/src/main/java/com/acorn/soso/support/controller/SupportController.java
- Soso/src/main/webapp/WEB-INF/views/support/support_faq.jsp
- Soso/src/main/webapp/WEB-INF/views/support/support_main.jsp
- Soso/src/main/webapp/resources/css/support/support_main.css
8월 16일 faq 자주하는 질문 등록 및 출력 기능 추가
> 8월16일 faq 및 고객센터 메인 기능 일부 구현

- Soso/src/main/webapp/WEB-INF/views/group/detail.jsp
- Soso/src/main/webapp/WEB-INF/views/group/group_page.jsp
- Soso/src/main/webapp/WEB-INF/views/group/list.jsp
- Soso/src/main/webapp/WEB-INF/views/group_managing/admin_main.jsp
- Soso/src/main/webapp/WEB-INF/views/group_managing/applicantList.jsp
- Soso/src/main/webapp/WEB-INF/views/group_managing/group_insertForm.jsp
- Soso/src/main/webapp/WEB-INF/views/group_managing/group_updateForm.jsp
- Soso/src/main/webapp/WEB-INF/views/group_managing/user_main.jsp
- Soso/src/main/webapp/WEB-INF/views/include/navbar.jsp
- Soso/src/main/webapp/WEB-INF/views/include/navbar_c.jsp
- Soso/src/main/webapp/resources/css/common.css
- Soso/src/main/webapp/resources/css/group_list.css
- Soso/src/main/webapp/resources/css/group_managing/group_managing_group_insert.css
- Soso/src/main/webapp/resources/css/group_managing_user_main.css
- Soso/src/main/webapp/resources/css/group_page.css
> 230816/북메이트 관리 , 수정 UI 수정 진행중

- Soso/src/main/java/com/acorn/soso/group/service/GroupServiceImpl.java
- Soso/src/main/resources/mapper/GroupFAQmapper.xml
- Soso/src/main/webapp/WEB-INF/views/group/faq/list.jsp
- Soso/src/main/webapp/WEB-INF/views/group/group_page.jsp
> Groupdetail

- Soso/src/main/webapp/WEB-INF/views/support/support_faq.jsp
> 8월 17일 기능 추가

- Soso/src/main/webapp/WEB-INF/views/group/group_page.jsp
- Soso/src/main/webapp/resources/css/group_page.css
230818/소모임별 페이지에 가입신청, 찜하기 , 문의하기 하단 고정 플로팅 띄우기
> 230818/소모임별 페이지에 가입신청, 찜하기 , 문의하기 하단 고정 플로팅 띄우기

- Soso/src/main/webapp/WEB-INF/views/support/support_faq.jsp
- Soso/src/main/webapp/WEB-INF/views/support/support_faq_etc.jsp
- Soso/src/main/webapp/WEB-INF/views/support/support_faq_open.jsp
- Soso/src/main/webapp/WEB-INF/views/support/support_faq_request.jsp
- Soso/src/main/webapp/WEB-INF/views/support/support_faq_user.jsp
- Soso/src/main/webapp/WEB-INF/views/support/support_main.jsp
- Soso/src/main/webapp/WEB-INF/views/support/support_notice.jsp
- Soso/src/main/webapp/resources/css/support/support_faq.css
- Soso/src/main/webapp/resources/css/support/support_main.css
- Soso/src/main/webapp/resources/css/support/support_notice.css
8월18일 faq 질문 답변 기능 구현 완료 및 레이아웃 수정
> 8월18일 faq 질문 답변 기능 구현 완료 및 레이아웃 수정

- Soso/src/main/java/com/acorn/soso/support/controller/SupportController.java
- Soso/src/main/java/com/acorn/soso/support/dao/NoticeDao.java
- Soso/src/main/java/com/acorn/soso/support/dao/NoticeDaoImpl.java
- Soso/src/main/java/com/acorn/soso/support/dto/NoticeDto.java
- Soso/src/main/java/com/acorn/soso/support/service/NoticeService.java
- Soso/src/main/java/com/acorn/soso/support/service/NoticeServiceImpl.java
- Soso/src/main/resources/mapper/support/NoticeMapper.xml
- Soso/src/main/webapp/WEB-INF/views/support/support_main.jsp
- Soso/src/main/webapp/WEB-INF/views/support/support_notice.jsp
- Soso/src/main/webapp/WEB-INF/views/support/support_notice_insert.jsp
- Soso/src/main/webapp/WEB-INF/views/support/support_notice_insertform.jsp
> 8월18일 공지사항 등록 및 리스트 조회 기능 구현

- Soso/src/main/java/com/acorn/soso/group/controller/GroupController.java
- Soso/src/main/webapp/WEB-INF/views/group/ajax_list.jsp
- Soso/src/main/webapp/WEB-INF/views/group/list2.jsp
소모임 ajax 기능 list2페이지에서 확인 가능합니다.
> 소모임 리스트에 페이지네이션 대신 ajax리스트 갱신 사

- Soso/src/main/webapp/WEB-INF/views/cafe/list.jsp
- Soso/src/main/webapp/WEB-INF/views/group/list.jsp
- Soso/src/main/webapp/WEB-INF/views/group_managing/group_userdetail.jsp
- Soso/src/main/webapp/WEB-INF/views/home.jsp
- Soso/src/main/webapp/resources/css/group_managing_list.css
- Soso/src/main/webapp/resources/css/group_managing_user_detail.css
> Hn#230819 커뮤니티 ui 수정

- Soso/src/main/webapp/WEB-INF/views/group/faq/insertform.jsp
- Soso/src/main/webapp/WEB-INF/views/group/faq/list.jsp
- Soso/src/main/webapp/WEB-INF/views/group/faq/paginglist.jsp
- Soso/src/main/webapp/WEB-INF/views/group/faq/updateform.jsp
- Soso/src/main/webapp/resources/css/groupfaq.css
> group_page faq 게시판 레이아웃 insert update 수정

- Soso/src/main/java/com/acorn/soso/group/controller/GroupController.java
- Soso/src/main/webapp/WEB-INF/views/group/ajax_viewList.jsp
- Soso/src/main/webapp/WEB-INF/views/group/list.jsp
- Soso/src/main/webapp/WEB-INF/views/group/viewList.jsp
- Soso/src/main/webapp/WEB-INF/views/include/navbar_c.jsp
- Soso/src/main/webapp/WEB-INF/views/support/support_faq.jsp
- Soso/src/main/webapp/WEB-INF/views/support/support_faq_etc.jsp
- Soso/src/main/webapp/WEB-INF/views/support/support_faq_insertform.jsp
- Soso/src/main/webapp/WEB-INF/views/support/support_faq_open.jsp
- Soso/src/main/webapp/WEB-INF/views/support/support_faq_request.jsp
- Soso/src/main/webapp/WEB-INF/views/support/support_faq_updateform.jsp
- Soso/src/main/webapp/WEB-INF/views/support/support_faq_user.jsp
- Soso/src/main/webapp/WEB-INF/views/support/support_inquire.jsp
- Soso/src/main/webapp/WEB-INF/views/support/support_inquire_MyInquire.jsp
- Soso/src/main/webapp/WEB-INF/views/support/support_inquire_Myinquire_detail.jsp
- Soso/src/main/webapp/WEB-INF/views/support/support_main.jsp
- Soso/src/main/webapp/WEB-INF/views/support/support_notice.jsp
- Soso/src/main/webapp/resources/css/group_list.css
- Soso/src/main/webapp/resources/css/main.css
- Soso/src/main/webapp/resources/css/reset.css
- Soso/src/main/webapp/resources/css/support/support_faq.css
- Soso/src/main/webapp/resources/css/support/support_inquire.css
- Soso/src/main/webapp/resources/css/support/support_inquire_MyInquire.css
- Soso/src/main/webapp/resources/css/support/support_inquire_register.css
- Soso/src/main/webapp/resources/css/support/support_main.css
- Soso/src/main/webapp/resources/css/support/support_notice.css
230823/소모임 리스트 ajax처리 수정, 고객센터 메뉴바 수정
> 230823/소모임 리스트 ajax처리 수정, 고객센터 메뉴바 수정

- Soso/src/main/webapp/WEB-INF/views/group/list.jsp
스크롤 꼭 바닥에 닿지 않아도 ajax 호출되도록 설정
> ajax 리스트 갱신 약간 수정

- Soso/src/main/java/com/acorn/soso/group/service/GroupServiceImpl.java
- Soso/src/main/resources/mapper/GroupFAQmapper.xml
- Soso/src/main/resources/mapper/GroupMapper.xml
- Soso/src/main/webapp/WEB-INF/views/group/faq/list.jsp
소모임 관리자는 삭제가 가능하도록 하는 기능 수정. faq insert를 작성할 때 임의로 a_writer집어넣음(관리자 삭제를 가능하게 하기 위해서)
> 소모임 게시판 문의하기 페이지에서 작성자 외에 삭제 / 수정 가능하게 한 문제 수정 및

- Soso/pom.xml
> 0.1.2 release

- Soso/src/main/java/com/acorn/soso/group/dao/GroupJoinDaoImpl.java
- Soso/src/main/resources/mapper/JoinMapper.xml
- Soso/src/main/webapp/WEB-INF/views/group/jjim_list.jsp
> 23.09.05 소모임 가입 시 모임장이 자동가입될때 현재 가입 인원수에 반영되지 않던 문제 해결, 북마크 리스트 css 오류

- Soso/src/main/webapp/WEB-INF/views/support/support_inquire.jsp
- Soso/src/main/webapp/WEB-INF/views/support/support_notice_detail.jsp
- Soso/src/main/webapp/resources/css/support/support_inquire.css
- Soso/src/main/webapp/resources/css/support/support_notice_detail.css
> Feature/sub BOOKMATE-7

- Soso/pom.xml
- 고객센터 운영자 문의 답변 기능
- code clean up
- UI & bug fix
> 0.1.4 release

- Soso/src/main/webapp/WEB-INF/views/support/support_inquire_inquireStatus.jsp
- Soso/src/main/webapp/resources/css/support/support_faq.css
- Soso/src/main/webapp/resources/css/support/support_inquire_MyInquire.css
- Soso/src/main/webapp/resources/css/support/support_notice.css
- Soso/src/main/webapp/resources/css/support/support_notice_detail.css
> 9월11일 admin 관련 버튼 및 UI 수정 보완
